apiVersion: v1
kind: Service
metadata:
  labels:
    name: wpfrontend
  name: wpfrontend
spec:
  selector:
    name: wordpress
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 80
    name: open
  type: LoadBalancer
